trigger: none

pool:
 name: ado

jobs:
  - job: 
    displayName: Test1
    steps:
      - script: |
          hostname
  - job: 
    displayName: Test2
    steps:
        - script: |
            ip addr