trigger: none

pool:
 name: ado

jobs:
  - job: j1
    displayName: Test1
    steps:
      - script: |
          terraform init
      - script: |
          terraform fmt
      - script: |
          terraform validate
      - script: |
          terraform plan
      - script: |
          terraform appy -auto-approve